CREATE TABLE HEARTBEATS (
   OWNER VARCHAR(255) NOT NULL,
   INTERVAL_MILLIS bigint NOT NULL,
   LAST_HEARTBEAT_INSTANT_MILLIS bigint NOT NULL,
   PRIMARY KEY (OWNER),
   UNIQUE KEY HEARTBEATS_PK (OWNER)
);
