
CREATE TABLE SEMAPHORES (
  SEMAPHORE_NAME VARCHAR(255) NOT NULL PRIMARY KEY,
  AVAILABLE_PERMITS BIGINT NOT NULL,
  TOTAL_PERMITS BIGINT NOT NULL,
  LAST_UPDATED_BY VARCHAR(255) NOT NULL,
  LAST_UPDATED_AT BIGINT NOT NULL
);

CREATE TABLE PERMITS_BY_OWNER (
   SEMAPHORE_NAME VARCHAR(255) NOT NULL,
   OWNER VARCHAR(255) NOT NULL,
   PERMITS BIGINT NOT NULL,
   LAST_UPDATED_AT BIGINT NOT NULL,
   PRIMARY KEY (SEMAPHORE_NAME, OWNER),
   FOREIGN KEY (SEMAPHORE_NAME) REFERENCES SEMAPHORES(SEMAPHORE_NAME)
);
