/*
 * Copyright (c) 2001-2017, Zoltan Farkas All Rights Reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * Additionally licensed with:
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.spf4j.ui;
//CHECKSTYLE:OFF

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.event.ItemEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.LinkedList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import org.spf4j.base.Methods;
import org.spf4j.ssdump2.Converter;
import org.spf4j.stackmonitor.SampleNode;

/**
 * will need to add some standard filtering:
 *
 * Pair.of(sun.misc.Unsafe.class.getName(), "park")); Pair.of(java.lang.Object.class.getName(), "wait"));
 * Pair.of(java.lang.Thread.class.getName(), "sleep")); Pair.of("java.net.PlainSocketImpl", "socketAccept"));
 * Pair.of("java.net.PlainSocketImpl", "socketConnect"));
 *
 * @author zoly
 */
@SuppressFBWarnings({"FCBL_FIELD_COULD_BE_LOCAL", "SE_BAD_FIELD"})
class StackDumpJInternalFrame extends javax.swing.JInternalFrame {

  private SampleNode samples;

  /**
   * Creates new form StackDumpJInternalFrame
   */
  StackDumpJInternalFrame(final SampleNode samples,
          final String title, final boolean isgraph) {
    super(title);
    setName(title);
    initComponents();
    if (samples == null) {
      this.samples = SampleNode.createSampleNode(
              new StackTraceElement[]{new StackTraceElement("NO SAMPLES", "", "", -1)});
    } else {
      this.samples = samples;
    }
    setViewType(isgraph);
    ssScrollPanel.setVisible(true);
    pack();
  }

  private void setViewType(final boolean isgraph) {
    StackPanelBase view = (StackPanelBase) ssScrollPanel.getViewport().getView();
    if (isgraph) {
      graphToggle.setSelected(true);
      //ssScrollPanel.setViewportView(new ZStackPanel(this.samples));
      if (view != null) {
        ssScrollPanel.setViewportView(new HotFlameStackPanel(view.getMethod(), view.getSamples(), view.getHistory()));
      } else {
        ssScrollPanel.setViewportView(new HotFlameStackPanel(Methods.ROOT, this.samples, new LinkedList<>()));
      }
    } else {
      graphToggle.setSelected(false);
      if (view != null) {
        ssScrollPanel.setViewportView(new FlameStackPanel(view.getMethod(), view.getSamples(), view.getHistory()));
      } else {
        ssScrollPanel.setViewportView(new FlameStackPanel(Methods.ROOT, this.samples, new LinkedList<>()));
      }
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  @SuppressFBWarnings
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    ssScrollPanel = new javax.swing.JScrollPane();
    samplesVisualizerToolbar = new javax.swing.JToolBar();
    graphToggle = new javax.swing.JToggleButton();
    exportButton = new javax.swing.JButton();

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);

    ssScrollPanel.setAutoscrolls(true);

    samplesVisualizerToolbar.setRollover(true);

    graphToggle.setText("graph");
    graphToggle.setFocusable(false);
    graphToggle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    graphToggle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    graphToggle.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        graphToggleItemStateChanged(evt);
      }
    });
    samplesVisualizerToolbar.add(graphToggle);

    exportButton.setText("export");
    exportButton.setFocusable(false);
    exportButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    exportButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    exportButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        exportButtonActionPerformed(evt);
      }
    });
    samplesVisualizerToolbar.add(exportButton);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(ssScrollPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
      .add(samplesVisualizerToolbar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
        .add(samplesVisualizerToolbar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(ssScrollPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void graphToggleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_graphToggleItemStateChanged
    setViewType(evt.getStateChange() == ItemEvent.SELECTED);
  }//GEN-LAST:event_graphToggleItemStateChanged

  @SuppressFBWarnings({ "PATH_TRAVERSAL_IN", "RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE", "UP_UNUSED_PARAMETER" })
  // this is a local app, FB sees problems with Try -> {} genereted code......
  private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
    JFileChooser fc = new JFileChooser();
    FileFilter[] xFF = fc.getChoosableFileFilters();
    for (FileFilter ff : xFF) {
      fc.removeChoosableFileFilter(ff);
    }
    fc.addChoosableFileFilter(Spf4jFileFilter.D3_JSON);
    fc.addChoosableFileFilter(Spf4jFileFilter.SPF4J_JSON);
    fc.addChoosableFileFilter(Spf4jFileFilter.SSDUMP2);
    fc.addChoosableFileFilter(Spf4jFileFilter.SSDUMP2_GZ);
    fc.setFileFilter(Spf4jFileFilter.D3_JSON);
    int retrival = fc.showSaveDialog(null);
    if (retrival == JFileChooser.APPROVE_OPTION) {
      File selectedFile = fc.getSelectedFile();
      FileFilter fileFilter = fc.getFileFilter();
      if (!(fileFilter instanceof Spf4jFileFilter)) {
        throw new IllegalArgumentException("Invalid file type selected " + fileFilter);
      }
      String suffix = ((Spf4jFileFilter) fileFilter).getSuffix();
      if (!selectedFile.getName().endsWith(suffix)) {
        selectedFile = new File(selectedFile.getParentFile(), selectedFile.getName() + suffix);
      }
      if (Spf4jFileFilter.D3_JSON.accept(selectedFile)) { // D3 format.
        try (BufferedWriter wr = Files.newBufferedWriter(selectedFile.toPath(), StandardCharsets.UTF_8)) {
          samples.writeD3JsonTo(wr);
        } catch (IOException ex) {
          throw new UncheckedIOException(ex);
        }
      } else if (Spf4jFileFilter.SPF4J_JSON.accept(selectedFile)) {
        try (BufferedWriter wr = Files.newBufferedWriter(selectedFile.toPath(), StandardCharsets.UTF_8)) {
          samples.writeJsonTo(wr);
        } catch (IOException ex) {
          throw new UncheckedIOException(ex);
        }
      } else if (Spf4jFileFilter.SSDUMP2.accept(selectedFile) || Spf4jFileFilter.SSDUMP2_GZ.accept(selectedFile)) {
        try {
          Converter.save(selectedFile, samples);
        } catch (IOException ex) {
          throw new UncheckedIOException(ex);
        }
      } else {
        throw new IllegalArgumentException("No ecognized extension for file " + selectedFile);
      }
    }
  }//GEN-LAST:event_exportButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton exportButton;
  private javax.swing.JToggleButton graphToggle;
  private javax.swing.JToolBar samplesVisualizerToolbar;
  private javax.swing.JScrollPane ssScrollPanel;
  // End of variables declaration//GEN-END:variables
}
